#!/usr/bin/env python
# coding: utf-8

import cv2
import numpy as np



img = cv2.imread(r"C:\Users\walee\Documents\red_line_in_water.jpeg")
hsvImage = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
#binary_img = cv2.inRange(hsvImage, (150, 0, 20), (160, 255, 255))
binary_img = cv2.inRange(hsvImage, (170, 0, 0), (179, 255, 255))

cv2.imshow("image", img)
cv2.imshow('HSV image', hsvImage)

cv2.imshow('binary_img', binary_img)



indicies = np.nonzero(binary_img)

print(indicies[0]) # Y coordinate
print(indicies[1]) #X coordinate
l = len(indicies[1]) - 1
#point 1
y_int = indicies[0][0]
x1 = indicies[1][0]
x2 = indicies[1][l]
y2 = indicies[0][l]

slope = (y2-y_int)/(x2-x1)

print("Slope:")
print(slope)
print("Intercept:")
print(y_int)

xcen = indicies[1][round(l/2)]
ycen = indicies[0][round(l/2)]

print("Xcen is:" + str(xcen))
print("Ycen is:" + str(ycen))

#cv2.imshow('original', img)

cv2.waitKey(0) 
cv2.destroyAllWindows()


import cv2
import sys
import numpy as np

def nothing(x):
    pass

# Create a window
cv2.namedWindow('image')

# create trackbars for color change
cv2.createTrackbar('HMin','image',0,179,nothing) # Hue is from 0-179 for Opencv
cv2.createTrackbar('SMin','image',0,255,nothing)
cv2.createTrackbar('VMin','image',0,255,nothing)
cv2.createTrackbar('HMax','image',0,179,nothing)
cv2.createTrackbar('SMax','image',0,255,nothing)
cv2.createTrackbar('VMax','image',0,255,nothing)

# Set default value for MAX HSV trackbars.
cv2.setTrackbarPos('HMax', 'image', 179)
cv2.setTrackbarPos('SMax', 'image', 255)
cv2.setTrackbarPos('VMax', 'image', 255)

# Initialize to check if HSV min/max value changes
hMin = sMin = vMin = hMax = sMax = vMax = 0
phMin = psMin = pvMin = phMax = psMax = pvMax = 0

img = cv2.imread(r"C:\Users\walee\Documents\red_line_in_water.jpeg")
output = img
waitTime = 33

while(1): #This allows the user to specifically set the ideal filtering.

    # get current positions of all trackbars
    hMin = cv2.getTrackbarPos('HMin','image')
    sMin = cv2.getTrackbarPos('SMin','image')
    vMin = cv2.getTrackbarPos('VMin','image')

    hMax = cv2.getTrackbarPos('HMax','image')
    sMax = cv2.getTrackbarPos('SMax','image')
    vMax = cv2.getTrackbarPos('VMax','image')

    # Set minimum and max HSV values to display
    lower = np.array([hMin, sMin, vMin])
    upper = np.array([hMax, sMax, vMax])

    # Create HSV Image and threshold into a range.
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(hsv, lower, upper)
    output = cv2.bitwise_and(img,img, mask= mask)

    # Print if there is a change in HSV value
    if( (phMin != hMin) | (psMin != sMin) | (pvMin != vMin) | (phMax != hMax) | (psMax != sMax) | (pvMax != vMax) ):
        print("(hMin = %d , sMin = %d, vMin = %d), (hMax = %d , sMax = %d, vMax = %d)" % (hMin , sMin , vMin, hMax, sMax , vMax))
        phMin = hMin
        psMin = sMin
        pvMin = vMin
        phMax = hMax
        psMax = sMax
        pvMax = vMax

    # Display output image
    cv2.imshow('image',output)

    # Wait longer to prevent freeze for videos.
    if cv2.waitKey(waitTime) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()


